### ISSUE TITLE
'module' object has no attribute 'machine'

### ISSUE THREAD

**Issue by byron-hawkins** [Maratyszcza/NNPACK#112]
When I run `confu setup` (or the `configure.py` script directly), I get the following error:

    Traceback (most recent call last):
      File "./configure.py", line 4, in <module>
        import confu
      File "/home/sureau/lab/python/confu/__init__.py", line 35, in <module>
        from confu.platform import Platform
      File "/home/sureau/lab/python/confu/platform.py", line 230, in <module>
        host = Platform(detect_host())
      File "/home/sureau/lab/python/confu/platform.py", line 198, in detect_host
        import platform
      File "/home/sureau/lab/python/confu/platform.py", line 230, in <module>
        host = Platform(detect_host())
      File "/home/sureau/lab/python/confu/platform.py", line 199, in detect_host
        machine = platform.machine()
    AttributeError: 'module' object has no attribute 'machine'

The same things happens if I try to run the `setup.py` script for confu.

    > python --version
    Python 2.7.13

**Comment by byron-hawkins** [comment]
The problem is that this command does not work for users with a custom python directory:

    pip install --upgrade git+https://github.com/Maratyszcza/confu

In my `~/.pip/pip.conf`:

    [global]
    target=/home/sureau/lab/python  

The confu files all go the wrong places, and it ends up importing its own `platform.py` instead of the Python system module named `platform.py`.

**Comment by byron-hawkins** [comment]
I am able to install everything after removing the broken confu and reinstalling via `confu/setup.py` without using pip.
