### ISSUE TITLE
Build fails: No module named peachpy.x86_64

### ISSUE THREAD

**Issue by yurivict** [Maratyszcza/NNPACK#169]
I'm trying to build it on FreeBSD and it fails:
```
[20/45] cd /usr/ports/science/nnpack/work/.build && PYTHONPATH=/usr/ports/science/nnpack/work/NNPACK-c039579/deps/six:/usr/ports/science/nnpack/work/NNPACK-c039579/deps/enum: /usr/local/bin/python2.7 -m peachpy.x86_64 -mabi=sysv -g4 -mimage-format=elf -I/usr/ports/science/nnpack/work/NNPACK-c039579/src -I/usr/ports/science/nnpack/work/NNPACK-c039579/src/x86_64-fma -I/usr/local/include -o /usr/ports/science/nnpack/work/.build/src/x86_64-fma/2d-fourier-8x8.py.o /usr/ports/science/nnpack/work/NNPACK-c039579/src/x86_64-fma/2d-fourier-8x8.py
FAILED: src/x86_64-fma/2d-fourier-8x8.py.o 
cd /usr/ports/science/nnpack/work/.build && PYTHONPATH=/usr/ports/science/nnpack/work/NNPACK-c039579/deps/six:/usr/ports/science/nnpack/work/NNPACK-c039579/deps/enum: /usr/local/bin/python2.7 -m peachpy.x86_64 -mabi=sysv -g4 -mimage-format=elf -I/usr/ports/science/nnpack/work/NNPACK-c039579/src -I/usr/ports/science/nnpack/work/NNPACK-c039579/src/x86_64-fma -I/usr/local/include -o /usr/ports/science/nnpack/work/.build/src/x86_64-fma/2d-fourier-8x8.py.o /usr/ports/science/nnpack/work/NNPACK-c039579/src/x86_64-fma/2d-fourier-8x8.py
/usr/local/bin/python2.7: No module named peachpy.x86_64
ninja: build stopped: subcommand failed.
```

**Comment by Maratyszcza** [comment]
How do you build it? Do you use CMake?

**Comment by yurivict** [comment]
I use cmake w/in the FreeBSD ports framework.

**Comment by Maratyszcza** [comment]
NNPACK CMake file should download PeachPy and add it to `PYTHONPATH`, see [here](https://github.com/Maratyszcza/NNPACK/blob/master/CMakeLists.txt#L161), but I see only `PYTHONPATH=/usr/ports/science/nnpack/work/NNPACK-c039579/deps/six:/usr/ports/science/nnpack/work/NNPACK-c039579/deps/enum:` in your logs. Do you pass `-DPYTHON_PEACHPY_SOURCE_DIR` to CMake (you shouldn't)? Please paste a complete log, including the commands you type.

**Comment by yurivict** [comment]
PeachPy package is pre-installed, insecure downloads aren't allowed during the package builds.

**Comment by Maratyszcza** [comment]
Did you follow installation instructions in [PeachPy README](https://github.com/Maratyszcza/PeachPy)?

**Comment by yurivict** [comment]
yes, setup.py does all the work there.

**Comment by Maratyszcza** [comment]
Try a simple test, e.g. `python -c "from peachpy.x86_64 import * ; ADD(eax, 5).encode()"`

**Comment by Maratyszcza** [comment]
Actually, `/usr/local/bin/python2.7 -c "from peachpy.x86_64 import * ; ADD(eax, 5).encode()"` in your case, because this is the Python CMake finds.

**Comment by yurivict** [comment]
```py27-peachpy``` installs ```x64``` and ```x86``` architectures.

```
$ python2.7 -c "from peachpy.x64 import * ; ADD(eax, 5).encode()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/peachpy/x64.py", line 8939, in ADD
    origin = inspect.stack() if Function.get_current().collect_origin else None
  File "/usr/local/lib/python2.7/site-packages/peachpy/x64.py", line 625, in get_current
    raise ValueError('No function is active')
ValueError: No function is active
```

```
$ python2.7 -c "from peachpy.x86 import * ; ADD(eax, 5).encode()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/peachpy/x86.py", line 2945, in ADD
    current_function.add_instruction(ArithmeticInstruction('ADD', Operand(destination), Operand(source)))
AttributeError: 'NoneType' object has no attribute 'add_instruction'
```

**Comment by Maratyszcza** [comment]
**DO NOT** install PeachPy from PyPI. It is an old version, incompatible with NNPACK. Follow the instructions in [PeachPy README](https://github.com/Maratyszcza/PeachPy#installation)

**Comment by yurivict** [comment]
The new version of ```PeachPy``` fixed this, thanks!
