### ISSUE TITLE
Cannot compile on linux-x86-64

### ISSUE THREAD

**Issue by znsoftm** [Maratyszcza/NNPACK#182]
(base) root@mydl:~/NNPACK# python configure.py 
Detected root directory: /root/NNPACK
/var/anaconda3/lib/python3.7/site-packages/confu/manifest.py:36: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  manifest_yaml = yaml.load(manifest_text)
Configuring dependency pthreadpool
Configuring dependency fxdiv
Configuring dependency googletest
Configuring dependency googlebenchmark
Traceback (most recent call last):
  File "configure.py", line 482, in <module>
    main(sys.argv[1:]).generate()
  File "configure.py", line 46, in main
    (build.deps.pthreadpool, build.deps.cpuinfo, build.deps.fxdiv, build.deps.fp16): any,
  File "/var/anaconda3/lib/python3.7/site-packages/confu/builds/deps.py", line 48, in __getattr__
    config = configure.main(["--target", self._target])
  File "/root/NNPACK/deps/pthreadpool/configure.py", line 20, in main
    build.static_library("pthreadpool", [build.cc(src) for src in sources])
  File "/root/NNPACK/deps/pthreadpool/configure.py", line 20, in <listcomp>
    build.static_library("pthreadpool", [build.cc(src) for src in sources])
  File "/var/anaconda3/lib/python3.7/site-packages/confu/builds/unix.py", line 72, in cc
    return self._compile("cc", source_path)
  File "/var/anaconda3/lib/python3.7/site-packages/confu/builds/unix.py", line 56, in _compile
    source_path = validate_source_path(source_path, self.source_dir)
  File "/var/anaconda3/lib/python3.7/site-packages/confu/validators.py", line 67, in validate_source_path
    .format(source_path=source_path))
ValueError: Specified source file /root/NNPACK/deps/pthreadpool/src/threadpool-legacy.c does not exist

**Comment by znsoftm** [comment]
Actually, there was a version can be compiled under linux a few days ago. I  observed there are some change  in  threadpool.

**Comment by Maratyszcza** [comment]
Please try to build with CMake. I'm going to deprecate confu builds.
