### ISSUE TITLE
Wrong arg in configure.py for *nacl* hosts

### ISSUE THREAD

**Issue by omimo** [Maratyszcza/NNPACK#49]
Trying to run configure.py for x86_64-nacl-newlib hosts on osx, gives the following error:

``` 
$python ./configure.py --host=x86_64-nacl-newlib
Traceback (most recent call last):
  File "./configure.py", line 866, in <module>
    sys.exit(main())
  File "./configure.py", line 590, in main
    config.module(nnpack_objects + nacl_module_objects, "nnpack", lib_dirs=["$pepper_lib_dir"], libs=["ppapi"])
TypeError: module() got an unexpected keyword argument 'libs'
```

Upon looking at the configure.py, I realized that the line

```
nacl_module_binary = \
            config.module(nnpack_objects + nacl_module_objects, "nnpack", lib_dirs=["$pepper_lib_dir"], libs=["ppapi"])
```

has to change to

```
        nacl_module_binary = \
            config.module(nnpack_objects + nacl_module_objects, "nnpack", lib_dirs=["$pepper_lib_dir"],  extra_ldlibs=["ppapi"])
```

**Comment by Maratyszcza** [comment]
Thanks!
