### ISSUE TITLE
ubuntu x86-64 INTERL I5, last step ninja error

### ISSUE THREAD

**Issue by sunjunlishi** [Maratyszcza/NNPACK#67]
configure.py:

parser.add_argument("--backend", dest="backend", default="psimd",
                    choices=["auto", "psimd", "scalar"])

so i select psimd

result:
 ninja
[0/1] CONFIGURE 
Detected root directory: /home/sun/下载/NNPACK
Configuring dependency pthreadpool
Configuring dependency fxdiv
Configuring dependency googletest
Configuring dependency googlebenchmark
Configuring dependency fp16
Configuring dependency psimd
Module default: 1 libraries, 5 executables, 45 tests (11 smoke tests)
[35/150] PEACHPY bench/memread.py
FAILED: /home/sun/下载/NNPACK/build/bench/memread.py.o 
python -m peachpy.x86_64 -mabi=sysv -g4 -mimage-format=elf  -I/home/sun/下载/NNPACK/include -I/home/sun/下载/NNPACK/src/x86_64-fma -I/home/sun/下载/NNPACK/src -I/home/sun/下载/NNPACK/src/ref -I/home/sun/下载/NNPACK/test -I/home/sun/下载/NNPACK/bench -I/home/sun/下载/NNPACK/include -I/home/sun/下载/NNPACK/deps/pthreadpool/include -MMD -MF '/home/sun/下载/NNPACK/build/bench/memread.py.o'.d -o '/home/sun/下载/NNPACK/build/bench/memread.py.o' '/home/sun/下载/NNPACK/bench/memread.py'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/peachpy/x86_64/__main__.py", line 280, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/peachpy/x86_64/__main__.py", line 267, in main
    execute_script(writers, options.input[0])
  File "/usr/local/lib/python2.7/dist-packages/peachpy/x86_64/__main__.py", line 198, in execute_script
    execute_script(writers, source_filename)
  File "/usr/local/lib/python2.7/dist-packages/peachpy/writer.py", line 98, in __exit__
    self.output_file.write(self.encode())
  File "/usr/local/lib/python2.7/dist-packages/peachpy/writer.py", line 125, in encode
    return self.image.as_bytearray
  File "/usr/local/lib/python2.7/dist-packages/peachpy/formats/elf/image.py", line 59, in as_bytearray
    self.strtab.add(symbol.name)
  File "/usr/local/lib/python2.7/dist-packages/peachpy/formats/elf/section.py", line 209, in add
    string_bytes = codecs.encode(string, "utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 10: ordinal not in range(128)
[40/150] CXX test/convolution-input-gradient/alexnet.cc
ninja: build stopped: subcommand failed.

**Comment by sunjunlishi** [comment]
ok,i find the renson.because the folder name was chinese , i change "下载" to "down",ok
thanks

**Comment by sunjunlishi** [comment]
[156/156] LINK bin/convolution-inference+relu-smoketest
