### ISSUE TITLE
can't find googletest/confu.yaml

### ISSUE THREAD

**Issue by nopattern** [Maratyszcza/NNPACK#68]
Hi, @Maratyszcza I am trying to build nnpack  and compiler output :

> No such file or directory: '/home/deep/work/NNPACK_rel/NNPACK/pthreadpool/deps/googletest/confu.yaml'

 Can you tell me where to find confu version of googletest? Thank you .

**Comment by Maratyszcza** [comment]
You seem to have a strange directory structure. Did you follow the README instructions?

I think you need to run `confu setup` in top-level NNPACK directory, then `./configure.py` and `ninja`.

**Comment by nopattern** [comment]
Thank you . It's the `confu setup`.

**Comment by wql15** [comment]
Hi, @Maratyszcza. I get the similar error when building nnpack, and the output is: 
`$ confu setup
Reuse dependency pthreadpool from /root/nnpack/NNPACK/deps/pthreadpool
Reuse dependency pthreadpool:fxdiv from  /root/nnpack/NNPACK/deps/fxdiv
Reuse dependency pthreadpool:fxdiv:googletest from /root/nnpack/NNPACK/deps/googletest
Fatal error: failed to read project manifest /root/nnpack/NNPACK/deps/googletest/confu.yaml: 
Traceback (most recent call last):
  File "/usr/local/bin/confu", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/confu/__main__.py", line 84, in main
    options.process(options, unparsed_args)
  File "/usr/local/lib/python2.7/site-packages/confu/__main__.py", line 70, in setup_deps
    setup_project_deps(root_dir, root_dir)
  File "/usr/local/lib/python2.7/site-packages/confu/__main__.py", line 65, in setup_project_deps
    namespace=dep.name if not namespace else namespace + ":" + dep.name)
  File "/usr/local/lib/python2.7/site-packages/confu/__main__.py", line 65, in setup_project_deps
    namespace=dep.name if not namespace else namespace + ":" + dep.name)
  File "/usr/local/lib/python2.7/site-packages/confu/__main__.py", line 65, in setup_project_deps
    namespace=dep.name if not namespace else namespace + ":" + dep.name)
  File "/usr/local/lib/python2.7/site-packages/confu/__main__.py", line 34, in setup_project_deps
    project = confu.manifest.Project.from_root(project_dir)
  File "/usr/local/lib/python2.7/site-packages/confu/manifest.py", line 29, in from_root
    with open(manifest_path) as manifest_file:
IOError: [Errno 2] No such file or directory: '/root/nnpack/NNPACK/deps/googletest/confu.yaml'`

Thank you in advance for your help.

**Comment by Maratyszcza** [comment]
Something is messed up in your `deps` directory, removing it and doing `confu setup` again should fix it.
