### ISSUE TITLE
Missing fft-block-mac.py for x86_64-fma

### ISSUE THREAD

**Issue by Kowasaki** [Maratyszcza/NNPACK#90]
Hello,

When I run configure.py, I get the following error:

`Traceback (most recent call last):
  File "./configure.py", line 396, in <module>
    main(sys.argv[1:]).generate()
  File "./configure.py", line 71, in main
    build.peachpy("x86_64-fma/fft-block-mac.py"),
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/unix.py", line 72, in peachpy
    source_path = validate_source_path(source_path, self.source_dir)
  File "/usr/local/lib/python2.7/dist-packages/confu/validators.py", line 67, in validate_source_path
    .format(source_path=source_path))
ValueError: Specified source file /home/weiyinko/Github/NNPACK/src/x86_64-fma/fft-block-mac.py does not exist`

When I checked inside the directory, that file indeed does not exist. Is it ok if I comment out 
`build.peachpy("x86_64-fma/fft-block-mac.py")` in configure.py or would that cause issues?

**Comment by Maratyszcza** [comment]
Should be fixed with 73af62e08af4464de68591dcda056890413a50d7
